Minor fixups (#275)
* Add missing brackets in rnn

* Fix random_uniform_variable

* Add name to pool op

* Remove return from switch initializer

* Build docs on Windows

* Use correct error class in invalid Dot

* Allow use of ceil() in dimension calculations

* Doc tweaks for UNIX-y systems

* Remove return in BatchFlatten

diff --git a/docs/BUILD b/docs/BUILD
--- a/docs/BUILD
+++ b/docs/BUILD
@@ -4,17 +4,31 @@ package(default_visibility = ["//visibility:public"])
 
 genrule(
     name = "docs",
-    local = 1,
-    srcs = ["conf.py", "requirements.txt"] +
-        glob(["**/*.rst"], exclude = ["venv/**"]),
+    srcs = [
+        "conf.py",
+        "requirements.txt",
+    ] + glob(
+        ["**/*.rst"],
+        exclude = ["venv/**"],
+    ),
     outs = ["docs.zip"],
     cmd = """
         CWD=`pwd`
         cd $$(dirname $(location conf.py))
         virtualenv --clear venv
-        venv/bin/python -m pip install -r requirements.txt
-        venv/bin/python -m sphinx -a -E -b html . _build/html
+        VIRTUAL_ENV_DISABLE_PROMPT=1
+        if [ -e 'venv/bin/activate' ]; then
+          . venv/bin/activate
+        elif [ -e 'venv/Scripts/activate' ]; then
+          . venv/Scripts/activate
+        else
+          echo 'Unable to enter virtual python environment'
+          exit 1
+        fi
+        python -m pip install -r requirements.txt
+        python -m sphinx -a -E -b html . _build/html
         cd _build/html
         zip -q -r $$CWD/$@ ./
     """,
+    local = 1,
 )
